repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v4.4.0"
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: trailing-whitespace
  - id: check-ast
  - id: check-yaml
    exclude: "\\.(svg|vtk|vtp)$"

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
    - id: ruff
      args: ["--fix", "--show-fixes",  "--line-length=120"]
    - id: ruff-format

- repo: https://github.com/asottile/pyupgrade
  rev: v3.2.2
  hooks:
  - id: pyupgrade
    args: [--py39-plus]